name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.14.1
      with:
        registry: ghcr.io
        username: unsstrennen
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true # Will only build if this is not here
        tags: |
          ghcr.io/unsstrennen/bitrix24_timeman_bot:latest
    - name: Run Docker CMD
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_USER }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ghcr.io/unsstrennen/bitrix24_timeman_bot:latest
          docker rm -f bitrix24_timeman || true
          docker run -d ghcr.io/unsstrennen/bitrix24_timeman_bot:latest -e BASE_HOST=$HOST -e TOKEN=$TOKEN --name bitrix24_timeman
